name = "typegpt-weights"
main = "./workers/typegpt-weights/src/index.ts"
compatibility_date = "2026-05-02"

[[r2_buckets]]
binding = "TYPEGPT_WEIGHTS"
bucket_name = "typegpt-weights"

[[routes]]
pattern = "weights.typegpt.dev"
custom_domain = true

[vars]
ALLOWED_ORIGINS = "https://typegpt.dev,http://localhost:*,http://127.0.0.1:*"
